version: "2.1"
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # Specify a timezone to use
    volumes:
      - ${MEDIA_PATH}:/data/media
    # ports:
    #   - 6767:6767
    restart: unless-stopped
