version: "2.1"
services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # Specify a timezone to use
    volumes:
      - ${CONFIG_PATH}/bazarr:/config
      - ${ROOT}/:/data
    ports:
      - 6767:6767
    restart: unless-stopped