version: "3.7"
services:
  caddy:
    image: caddy
    container_name: caddy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # Specify a timezone to use
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${CADDY_FILES}/Caddyfile:/etc/caddy/Caddyfile
      - ${CADDY_FILES}/caddy_security.conf:/etc/caddy/caddy_security.conf

      # assets
      - ${CADDY_FILES}/sites/assets:/srv/sites/landing-page/assets
      - ${CADDY_FILES}/sites/assets:/srv/sites/soon/assets

      # sites
      - ${CADDY_FILES}/sites/landing-page:/srv/sites/landing-page
      - ${CADDY_FILES}/sites/soon:/srv/sites/soon

      - ${CONFIG_PATH}:/config
      - caddy-data:/data
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
