version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      # - ${CONFIG_PATH}/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - ${CONFIG_PATH}/caddy:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config:
