version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # Specify a timezone to use
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/Caddyfile:/etc/caddy/Caddyfile

      # Sites
      - ${PWD}/sites/assets:/srv/sites/landing-page/assets
      - ${PWD}/sites/assets:/srv/sites/soon/assets
      - ${PWD}/sites/landing-page:/srv/sites/landing-page
      - ${PWD}/sites/soon:/srv/sites/soon

      - ${CONFIG_PATH}/caddy:/config
      - caddy_data:/data

volumes:
  caddy_data:
    external: true
  caddy_config:
