---
version: "3.9"
services:
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=022 #optional
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${CONFIG_PATH}/deluge:/config
      - ${TORRENT_DOWNLOAD}/:/data/torrents
    # ports:
    #   - 8112:8112 # webui
    #   - 58846:58846 # daemon
    #   - 6881:6881 # bittorrent
    #   - 6881:6881/udp # bittorrent
    restart: unless-stopped