version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server

      - 9117:9117 # Jackett

      # Deluge
      - 8112:8112 # webui
      - 58846:58846 # daemon
      - 6881:6881 # bittorrent
      - 6881:6881/udp # bittorrent

      # Sonarr
      - 8989:8989/tcp # Web UI

      # Radarr
      - 7878:7878

    # command:
    volumes:
      - ${CONFIG_PATH}/gluetun:/config
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      # More variables are available, see the Wiki table
      - VPNSP=${VPNSP}
      - VPN_TYPE=${VPN_TYPE}

      # - PUBLICIP_FILE=${PUBLICIP_FILE}
      - COUNTRY=${COUNTRY}
      - CITY=${CITY}
      - ISP=${ISP}
      - OWNED=${OWNED}
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESS=${WIREGUARD_ADDRESS}

      - TZ=${TZ} # Timezone for accurate logs times

    restart: always
