version: "2.1"
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # Specify a timezone to use
      # - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - ${CONFIG_PATH}/jackett:/config
      - ${DOWNLOAD_PATH}/blackhole:/data/torrents/blackhole
    ports:
      - 9117:9117
    restart: unless-stopped