version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/radarr:/config # Contains all relevant configuration files.
      - ${DATA_PATH}:/data
    # ports:
    #   - 7878:7878
    restart: unless-stopped