version: "2"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ} # Specify a timezone to use
    volumes:
      - ${CONFIG_PATH}/sonarr:/config # Contains all relevant configuration files.
      - ${ROOT}:/data # Location of all your media
      - ${DOWNLOAD_PATH}/tv:/data/downloads/torrents/tv
    ports:
      - 8989:8989/tcp # Web UI
    restart: unless-stopped
