# docker run -d --restart=always -p 3001:3001 -v uptime-kuma:/app/data --name uptime-kuma louislam/uptime-kuma:1
version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ${CONFIG_PATH}/uptime-kuma:/app/data
    ports:
      - 3001:3001

volumes:
  uptime-kuma:
    external: true